name: Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: 23f1003139@ds.study.iitm.ac.in
        run: echo "Hello, world!"
